// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wtHXqYo4cHDw1QkkqeK42j
// Component: RBWJ0uo_AlcZ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import FooterLink from "../../FooterLink"; // plasmic-import: A3mK7fgxYkXc/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: wtHXqYo4cHDw1QkkqeK42j/projectcss
import sty from "./PlasmicFooterLinksGroup.module.css"; // plasmic-import: RBWJ0uo_AlcZ/css

createPlasmicElementProxy;

export type PlasmicFooterLinksGroup__VariantMembers = {};
export type PlasmicFooterLinksGroup__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooterLinksGroup__VariantsArgs;
export const PlasmicFooterLinksGroup__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFooterLinksGroup__ArgsType = {
  groupName?: React.ReactNode;
  links?: any;
};
type ArgPropType = keyof PlasmicFooterLinksGroup__ArgsType;
export const PlasmicFooterLinksGroup__ArgProps = new Array<ArgPropType>(
  "groupName",
  "links"
);

export type PlasmicFooterLinksGroup__OverridesType = {
  root?: Flex__<"div">;
  categoryNameContainer?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  footerLink?: Flex__<typeof FooterLink>;
};

export interface DefaultFooterLinksGroupProps {
  groupName?: React.ReactNode;
  links?: any;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooterLinksGroup__RenderFunc(props: {
  variants: PlasmicFooterLinksGroup__VariantsArgs;
  args: PlasmicFooterLinksGroup__ArgsType;
  overrides: PlasmicFooterLinksGroup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          links: [{ url: "#", label: "Hello" }]
        },
        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"categoryNameContainer"}
        data-plasmic-override={overrides.categoryNameContainer}
        className={classNames(projectcss.all, sty.categoryNameContainer)}
      >
        {renderPlasmicSlot({
          defaultContents: "Enter some text",
          value: args.groupName,
          className: classNames(sty.slotTargetGroupName)
        })}
      </div>
      <Stack__
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
          (() => {
            try {
              return $props.links;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
        ).map((__plasmic_item_0, __plasmic_idx_0) => {
          const currentItem = __plasmic_item_0;
          const currentIndex = __plasmic_idx_0;
          return (
            <FooterLink
              data-plasmic-name={"footerLink"}
              data-plasmic-override={overrides.footerLink}
              className={classNames("__wab_instance", sty.footerLink)}
              key={currentIndex}
              label={(() => {
                try {
                  return currentItem.label;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              url={(() => {
                try {
                  return currentItem.url;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            />
          );
        })}
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "categoryNameContainer", "freeBox", "footerLink"],
  categoryNameContainer: ["categoryNameContainer"],
  freeBox: ["freeBox", "footerLink"],
  footerLink: ["footerLink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  categoryNameContainer: "div";
  freeBox: "div";
  footerLink: typeof FooterLink;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterLinksGroup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterLinksGroup__VariantsArgs;
    args?: PlasmicFooterLinksGroup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFooterLinksGroup__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFooterLinksGroup__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooterLinksGroup__ArgProps,
          internalVariantPropNames: PlasmicFooterLinksGroup__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooterLinksGroup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterLinksGroup";
  } else {
    func.displayName = `PlasmicFooterLinksGroup.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterLinksGroup = Object.assign(
  // Top-level PlasmicFooterLinksGroup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    categoryNameContainer: makeNodeComponent("categoryNameContainer"),
    freeBox: makeNodeComponent("freeBox"),
    footerLink: makeNodeComponent("footerLink"),

    // Metadata about props expected for PlasmicFooterLinksGroup
    internalVariantProps: PlasmicFooterLinksGroup__VariantProps,
    internalArgProps: PlasmicFooterLinksGroup__ArgProps
  }
);

export default PlasmicFooterLinksGroup;
/* prettier-ignore-end */
